export enum ServiceType {
  REMOVAL = 'REMOVAL',
  CLEANING = 'CLEANING',
  COATING = 'COATING',
  DESIGN = 'DESIGN',
  BUILD_UP = 'BUILD_UP',
  REINFORCEMENT = 'REINFORCEMENT',
  FRENCH = 'FRENCH',
  PEDICURE = 'PEDICURE',
}
